### ISSUE TITLE
Illegal moves

### ISSUE THREAD

**Issue by tpoppins** [stnevans/Apollo#7] opened 2018-09-30 18:12 UTC
Happens sporadically under Cute Chess GUI, much less frequent than  the crashes.
OS, GUI and setup same as in the "Cnstant crashes" issue.

In the example below Apollo drops its queen on the first move out of the book and seems to want to switch from playing White to playing Black.
```
[Event "?"]
[Site "?"]
[Date "2018.09.30"]
[Round "?"]
[White "Apollo 1.2.0 64-bit"]
[Black "BACE 0.46"]
[Result "0-1"]
[ECO "A40"]
[GameDuration "00:00:19"]
[GameEndTime "2018-09-30T13:28:54.071 Eastern Daylight Time"]
[GameStartTime "2018-09-30T13:28:35.047 Eastern Daylight Time"]
[Opening "Modern defense"]
[PlyCount "16"]
[Termination "illegal move"]
[TimeControl "40/120"]

1. d4 {book} g6 {book} 2. e4 {book} Bg7 {book} 3. c4 {book} d6 {book}
4. Nf3 {book} Bg4 {book} 5. Nc3 {book} Nc6 {book} 6. d5 {book} Nd4 {book}
7. Qa4+ {+0.11/13 3.2s} Bd7 {0.00/9 3.9s} 8. Nxd4 {+0.11/12 2.3s}
Bxa4 {+5.30/9 3.9s, White makes an illegal move: g7d4} 0-1


```

Debug log: https://pastebin.com/vXj8R6e7

**Comment by stnevans** [comment] 2018-09-30 23:15
Thanks for the log, I am able to reproduce this. The reason is that apollo doesn't properly understand the move Bxa4. Working on a fix.

**Comment by stnevans** [comment] 2018-10-01 00:26
Should be fixed in latest version.

**Closed as completed by stnevans** 2018-10-01 00:26 UTC
